version: "3.9"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    hostname: s3
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - test-bucket.s3.localhost.localstack.cloud
    #network_mode: bridge
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,secretsmanager
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  web:
    read_only: false
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    image: "authen-totp-webapp:latest"
    ports:
      - '8080:8080'
    expose:
      - 8080
    entrypoint: ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
    volumes:
      - ${PWD}/httpd.conf:/etc/httpd/conf/httpd.conf
      - ${HOME:?set HOME}/scratch:/tmp/scratch
